### ISSUE TITLE
Cannot get the software to run under Windows 3.11 for Workgroups.

### ISSUE THREAD

**Issue by TiberiuD** [pandrei7/passm#1]
As stated, your software should run under **any** version of Windows.

As my workflow requires it, I really wanted to use the Password Manager alongside Netscape Navigator 3.0, but unfortunately I couldn't. I'm getting an error about WS2_32.DLL not being found. I had a friend send it to me, but it didn't work. Apparently it's a 32-bit binary. What on earth, what's this 32-bit nonsense. Nobody would ever want more than 16-bit OS's...

![windows 3 1](https://user-images.githubusercontent.com/10258201/39684411-5fd021cc-51c4-11e8-8346-1c0c8b2318d1.PNG)

**Comment by pandrei7** [comment]
Thanks for contributing! The text file which mentioned the supported platforms was supposed to say that the program runs under any version of Windows **newer than Windows 7**. This issue has been fixed.

In regards to your understandable wish to run the app on Windows 3.11, I'm sorry to say it cannot be done. I do not plan to add support for older versions of Windows anytime soon, so, unless you come up with a solution (which I know you can do), the 16-bit goodness will have to wait. 😃
